config/routes.rb
Rails.application.routes.draw do

  resources :successful_pages
  get 'successful_pages' => 'successful_pages#index' 

  resources :carts, only: [:show]
  get 'cart' => 'carts#show'

  resources :order_items, only: [:create, :update, :destroy]

  resources :orders, only: [:update]

  resources :food_items
  get 'food_items' => 'food_items#index'

  get 'food_items/:id' => 'food_items#show'

  resources :contact_us
  get 'contact_us' => 'contact_us#index'

  resources :menus
  	get 'menus' => 'menus#index'

  get 'home/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food_item.rb
class FoodItem < ApplicationRecord
  belongs_to :section
  has_many :order_items

  def self.search(query)
    where("name ilike ?", "%#{query}%") 
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :order_status
  has_many :order_items
  before_validation :set_order_status
  before_save :update_subtotal

  def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end
private
  def set_order_status
    self.order_status_id = 1
  end

  def update_subtotal
    self[:subtotal] = subtotal
  end
  
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :food_item
  belongs_to :order

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :food_item_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      food_item.price
    end
  end

  def total_price
    unit_price * quantity
  end

private
  def food_item_present
    if food_item.nil?
      errors.add(:food_item, "is not valid.")
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end
end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
	has_many :orders
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
end

app/models/section.rb
class Section < ApplicationRecord
	has_many :food_items, dependent: :destroy

	def self.search(query)
    	# where(:title, query) -> This would return an exact match of the query
    	where("name ilike ?", "%#{query}%") 
  	end
  	def to_param
  	"#{name}"
	end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
  	@order = current_order
  	if @order.nil?
  		@order = Order.new
  	end
  	@order_items = @order.order_items
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  def index
  	@sections = Section.all
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def update
  	@order = current_order
  	if @order.update_attributes(order_params)
  		redirect_to successful_pages_path
  	end

  end

 private
  def order_params
  	params.require(:order).permit(:customer_name, :customer_phone_number, :customer_address, :customer_email)
  end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :set_section, only: [:edit, :update, :destroy]

  # GET /sections
  # GET /sections.json
  def index
      @sections = Section.all
  end

  # GET /sections/1
  # GET /sections/1.json
  def show
    # You could add a check to see if id is a string or an integer
    @section = Section.where(name: params[:id].titlecase).first 
    if params[:sort_by]
      @sort_by = params[:sort_by]
      @sort_order = 1
      if params[:sort_order] && "desc".casecmp(params[:sort_order])
        @sort_order = -1
      end

      @temp = @section.food_items

      case @sort_by
        when "name"
          @temp = @temp.sort_by {|f| f[:name].downcase}
        when "price"
          @temp = @temp.sort_by {|f| f[:price] * @sort_order}
        else
      end
      logger.debug "FIRST IS: #{@temp.first.name}"
      logger.debug "ACTUAL FIRST IS: #{@section.food_items.first.name}"
      @section.food_items = @temp
    end
  end

  # GET /sections/new
  def new
    @section = Section.new
  end

  # GET /sections/1/edit
  def edit
  end

  # POST /sections
  # POST /sections.json
  def create
    @section = Section.new(section_params)

    respond_to do |format|
      if @section.save
        format.html { redirect_to @section, notice: 'Section was successfully created.' }
        format.json { render :show, status: :created, location: @section }
      else
        format.html { render :new }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sections/1
  # PATCH/PUT /sections/1.json
  def update
    respond_to do |format|
      if @section.update(section_params)
        format.html { redirect_to @section, notice: 'Section was successfully updated.' }
        format.json { render :show, status: :ok, location: @section }
      else
        format.html { render :edit }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sections/1
  # DELETE /sections/1.json
  def destroy
    @section.destroy
    respond_to do |format|
      format.html { redirect_to sections_url, notice: 'Section was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_section
      @section = Section.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def section_params
      params.require(:section).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/contact_us_helper.rb
module ContactUsHelper
end

app/helpers/food_items_helper.rb
module FoodItemsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/successful_pages_helper.rb
module SuccessfulPagesHelper
end

app/views/carts/_cart_row.html.erb
<div class="well">

  <div class="row">
    <div class="col-xs-8">
      <h4><%= food_item.name %></h4>
    </div>
    <div class="col-xs-4">
      
      <%= form_for order_item, remote: true do |f| %>
        <h4 class="text-right">Unit Price: <span style="color: green"><%= number_with_delimiter order_item.unit_price %> VND</span></h4>
        <div class="row">
          <div class="col-xs-4">
            <%= f.number_field :quantity, value: order_item.quantity.to_i, class: "form-control", min: 1 %>
            <%= f.hidden_field :food_item_id, value: food_item.id %>
          </div>
          <div class="col-xs-8 text-right">
            <div class="btn-group">
              <%= f.submit "Update Quantity", class: "btn btn-primary" %>
              <%= link_to "Delete", order_item, { data: { confirm: "Are you sure you wish to delete the food item '#{order_item.food_item.name}' from your cart?" }, method: :delete, remote: true, class: "btn btn-danger" } %>
            </div>
          </div>
        </div>
        <h4 class="text-right">Total Price: <span style="color: green"><%= number_with_delimiter order_item.total_price %> VND</span></h4>
      <% end %>
    </div>
    
  </div>
</div>

app/views/carts/_food_cart.html.erb
<% if !@order_item.nil? && @order_item.errors.any? %>
  <div class="alert alert-danger">
    <ul>
    <% @order_item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<% if @order_items.size == 0 %>
  <p class="text-center">
    There are no food items in your cart.  Please <%= link_to "Go Back", food_items_path %> and add some food items to your cart.
  </p>
<% else %>
  <% @order_items.each do |order_item| %>
    <%= render 'carts/cart_row', food_item: order_item.food_item, order_item: order_item, show_total: true %>
  <% end %>
<% end %>

app/views/carts/show.html.erb
<div class="food-cart">
  <%= render "food_cart" %>
</div>
<div class="cart-customer-info">
<%= form_for @order do |f| %>
	  <div class="input-group">
		  <div class="form-group">
		  	<label for="customer_name">Customer Name:</label>
		    <%= f.text_field :customer_name, class: "form-control" %>
		  </div>
		  <div class="form-group">
			  <label for="customer_phone_number">Customer Phone Number:</label>
			  <%= f.text_field :customer_phone_number, class: "form-control" %>
		  </div>
		  <div class="form-group">
			  <label for="customer_address">Customer Address:</label>
		      <%= f.text_field :customer_address, class: "form-control" %>
		  </div>
		  <div class="form-group">
			  <label for="customer_email">Customer Email:</label>
		      <%= f.text_field :customer_email, class: "form-control" %>
		  </div>

		  <div class="form-group-btn">
		    <%= f.submit "Create Order", class: "btn btn-primary" %>
		  </div>
	  </div>
	<% end %>
</div>
  <%= link_to "go back", food_items_path %>

app/views/home/index.html.erb
      <div class="jumbotron banner">
        <div class="row">
		  <div class="col-sm-7">
		  	<p class="h4 text">Welcome to</p>
        	<h1 class="display-4 text">Lucky Clover Restaurant</h1>
        	<p>
        	<%= link_to "Menu", menus_path, class:"btn btn-default" %>
        	<%= link_to "Contact Us", contact_us_path, class:"btn btn-default" %>
        	</p>
		  </div>
		  <div class="col-sm-5">
			<img class="img img-fluid" src="https://charitydine-media.s3.amazonaws.com/thumbs/restaurant-images/c0f8e5ef19b1879ba3c5efef52a688449e1f8838_large.jpg"/>		  	
		  </div>
		</div>
      </div>

app/views/menus/index.html.erb
<div class="jumbotron banner">
    <ul>
    <% @sections.each do |section| %>
		<li>
		<%= link_to section.name, food_items_path(:type => "#{section.name}") %>
		</li>
	<% end %>
    </ul>
</div>