config/routes.rb
Rails.application.routes.draw do

  resources :successful_pages
  get 'successful_pages' => 'successful_pages#index' 

  resources :carts, only: [:show]
  get 'cart' => 'carts#show'

  resources :order_items, only: [:create, :update, :destroy]

  resources :orders, only: [:update]

  resources :food_items
  get 'food_items' => 'food_items#index'

  get 'food_items/:id' => 'food_items#show'

  resources :contact_us
  get 'contact_us' => 'contact_us#index'

  resources :menus
  	get 'menus' => 'menus#index'

  get 'home/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food_item.rb
class FoodItem < ApplicationRecord
  belongs_to :section
  has_many :order_items

  def self.search(query)
    where("name ilike ?", "%#{query}%") 
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :order_status
  has_many :order_items
  before_validation :set_order_status
  before_save :update_subtotal

  def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end
private
  def set_order_status
    self.order_status_id = 1
  end

  def update_subtotal
    self[:subtotal] = subtotal
  end
  
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :food_item
  belongs_to :order

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :food_item_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      food_item.price
    end
  end

  def total_price
    unit_price * quantity
  end

private
  def food_item_present
    if food_item.nil?
      errors.add(:food_item, "is not valid.")
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end
end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
	has_many :orders
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
end

app/models/section.rb
class Section < ApplicationRecord
	has_many :food_items, dependent: :destroy

	def self.search(query)
    	# where(:title, query) -> This would return an exact match of the query
    	where("name ilike ?", "%#{query}%") 
  	end
  	def to_param
  	"#{name}"
	end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
  	@order = current_order
  	if @order.nil?
  		@order = Order.new
  	end
  	@order_items = @order.order_items
  end
end

app/controllers/food_items_controller.rb
class FoodItemsController < ApplicationController
  def index
  	@order_str = "created_at"
  	if params[:sort_by]
      @sort_by = params[:sort_by]
      @sort_order = "ASC"
      if params[:sort_order]
        @sort_order = params[:sort_order]
      end
      @order_str = "#{@sort_by} #{@sort_order}"
    end

  	if params[:type]
  		@section = Section.where(name: params[:type].titlecase).first
  		@food_items = FoodItem.where(section: @section).order(@order_str)
  	elsif params[:search]
       @food_items = FoodItem.search(params[:search]).order(@order_str) 
    else
  		@food_items = FoodItem.all.order(@order_str)
  	end
    @order_item = current_order.order_items.new
  end

  def show
    @food_item = FoodItem.where(id: params[:id]).first
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  def index
  	@sections = Section.all
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def update
  	@order = current_order
  	if @order.update_attributes(order_params)
  		redirect_to successful_pages_path
  	end

  end

 private
  def order_params
  	params.require(:order).permit(:customer_name, :customer_phone_number, :customer_address, :customer_email)
  end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :set_section, only: [:edit, :update, :destroy]

  # GET /sections
  # GET /sections.json
  def index
      @sections = Section.all
  end

  # GET /sections/1
  # GET /sections/1.json
  def show
    # You could add a check to see if id is a string or an integer
    @section = Section.where(name: params[:id].titlecase).first 
    if params[:sort_by]
      @sort_by = params[:sort_by]
      @sort_order = 1
      if params[:sort_order] && "desc".casecmp(params[:sort_order])
        @sort_order = -1
      end

      @temp = @section.food_items

      case @sort_by
        when "name"
          @temp = @temp.sort_by {|f| f[:name].downcase}
        when "price"
          @temp = @temp.sort_by {|f| f[:price] * @sort_order}
        else
      end
      logger.debug "FIRST IS: #{@temp.first.name}"
      logger.debug "ACTUAL FIRST IS: #{@section.food_items.first.name}"
      @section.food_items = @temp
    end
  end

  # GET /sections/new
  def new
    @section = Section.new
  end

  # GET /sections/1/edit
  def edit
  end

  # POST /sections
  # POST /sections.json
  def create
    @section = Section.new(section_params)

    respond_to do |format|
      if @section.save
        format.html { redirect_to @section, notice: 'Section was successfully created.' }
        format.json { render :show, status: :created, location: @section }
      else
        format.html { render :new }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sections/1
  # PATCH/PUT /sections/1.json
  def update
    respond_to do |format|
      if @section.update(section_params)
        format.html { redirect_to @section, notice: 'Section was successfully updated.' }
        format.json { render :show, status: :ok, location: @section }
      else
        format.html { render :edit }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sections/1
  # DELETE /sections/1.json
  def destroy
    @section.destroy
    respond_to do |format|
      format.html { redirect_to sections_url, notice: 'Section was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_section
      @section = Section.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def section_params
      params.require(:section).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/contact_us_helper.rb
module ContactUsHelper
end

app/helpers/food_items_helper.rb
module FoodItemsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/successful_pages_helper.rb
module SuccessfulPagesHelper
end

app/views/food_items/_food_item.html.erb
<div class="card">
  <img class="card-img-top img-thumbnail" src="<%= food_item.imageUrl %>" alt="Card image cap">
  <div class="card-block">
    <h4 class="card-title"><%= food_item.name %></h4>

	<%= form_for order_item, remote: true do |f| %>
	  <h4 class="text-right">Unit Price: <span style="color: green"><%= number_with_delimiter food_item.price %> VND</span></h4>
	  <div class="input-group">
	    <%= f.number_field :quantity, value: 1, class: "form-control", min: 1 %>
	    <div class="input-group-btn">
	      <%= f.hidden_field :food_item_id, value: food_item.id %>
	      <%= f.submit "Add to Cart", class: "btn btn-primary" %>
	    </div>
	  </div>
	<% end %>
    <%= link_to "Detail", food_item_path(food_item.id), class: "btn btn-primary"%>

  </div>
</div>

app/views/food_items/index.html.erb
<p id="notice"><%= notice %></p>
<%= form_tag(food_items_path, :method => "get", class: "navbar-form", id: "search-form") do %>
    <div class="input-append">
      <%= text_field_tag :search, params[:search], class: "span2", placeholder: "Search Item" %>
      <%= submit_tag "Search" %>
    </div>
  <% end %>
<% if @food_items.present? %>
	<div style="margin-bottom: 1em">
		<p>Sort by: </p>
		<% @sort_by = params[:sort_by] %>
		<% @sort_order = params[:sort_order] %>

		<%= link_to "Alphabetical", params.merge(:sort_by => "name", :sort_order => "asc").permit!, 
						class: (@sort_by == "name" ? "btn btn-primary" : "btn btn-link") %>
		<%= link_to "Price Low To High", params.merge(:sort_by => "price", :sort_order => "asc").permit!,
						class: ((@sort_by == "price" && @sort_order != "desc") ? "btn btn-primary" : "btn btn-link") %>
		<%= link_to "Price High To Low", params.merge(:sort_by => "price", :sort_order => "desc").permit!,
						class: ((@sort_by == "price" && @sort_order == "desc") ? "btn btn-primary" : "btn btn-link") %>
	</div>
	<% @food_items.each do |food_item| %>
		<%= render "food_item", food_item: food_item, order_item: @order_item %>
	<% end %>
<% else %>
	<h2>No Food Is Found!!!</h2>
<% end %>
<%= link_to 'Back to Menu', menus_path %>

app/views/food_items/show.html.erb
<div class="card">
  <img class="card-img-top img-fluid" src="<%= @food_item.imageUrl %>" alt="Card image cap">
  <div class="card-block">
    <h4 class="card-title"><%= @food_item.name %></h4>
    <h4 class="card-subtitle"><%= @food_item.section.name %></h4>
    <p><%= @food_item.description %></p>
    <p class="card-text"><strong><%= number_with_delimiter(@food_item.price, :delimiter => ',') %> VND</strong></p>
  </div>
</div>