config/routes.rb
Rails.application.routes.draw do

  resources :successful_pages
  get 'successful_pages' => 'successful_pages#index' 

  resources :carts, only: [:show]
  get 'cart' => 'carts#show'

  resources :order_items, only: [:create, :update, :destroy]

  resources :orders, only: [:update]

  resources :food_items
  get 'food_items' => 'food_items#index'

  get 'food_items/:id' => 'food_items#show'

  resources :contact_us
  get 'contact_us' => 'contact_us#index'

  resources :menus
  	get 'menus' => 'menus#index'

  get 'home/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food_item.rb
class FoodItem < ApplicationRecord
  belongs_to :section
  has_many :order_items

  def self.search(query)
    where("name ilike ?", "%#{query}%") 
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :order_status
  has_many :order_items
  before_validation :set_order_status
  before_save :update_subtotal

  def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end
private
  def set_order_status
    self.order_status_id = 1
  end

  def update_subtotal
    self[:subtotal] = subtotal
  end
  
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :food_item
  belongs_to :order

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :food_item_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      food_item.price
    end
  end

  def total_price
    unit_price * quantity
  end

private
  def food_item_present
    if food_item.nil?
      errors.add(:food_item, "is not valid.")
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end
end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
	has_many :orders
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
end

app/models/section.rb
class Section < ApplicationRecord
	has_many :food_items, dependent: :destroy

	def self.search(query)
    	# where(:title, query) -> This would return an exact match of the query
    	where("name ilike ?", "%#{query}%") 
  	end
  	def to_param
  	"#{name}"
	end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
  	@order = current_order
  	if @order.nil?
  		@order = Order.new
  	end
  	@order_items = @order.order_items
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  def index
  	@sections = Section.all
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def update
  	@order = current_order
  	if @order.update_attributes(order_params)
  		redirect_to successful_pages_path
  	end

  end

 private
  def order_params
  	params.require(:order).permit(:customer_name, :customer_phone_number, :customer_address, :customer_email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/contact_us_helper.rb
module ContactUsHelper
end

app/helpers/food_items_helper.rb
module FoodItemsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/layouts/_cart_text.html.erb
<%= link_to "#{current_order.order_items.size} Items in Cart ( #{number_with_delimiter current_order.subtotal} VND)", cart_path(" "), class: "btn btn-link" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LuckyCloverRestaurant</title>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag 'favicon.ico' %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'home', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body data-gr-c-s-loaded="true">
    <div class="container">
    <div class="header clearfix">
      <div class="row">
        <div class="col-xs-6">
          <h1 style="text-decoration: none !important;"><%= link_to "Lucky Clover Restaurant", root_path %></h1>
        </div>
        <div class="col-xs-6 text-right">
          <h1 class="cart-text"><%= render 'layouts/cart_text' %></h1>
        </div>
      </div>
      </div>
      <%= yield %>
      <footer class="footer">
        <p>© DPQHUY 2016</p>
      </footer>
    </div> <!-- /container -->
  </body>
</html>